[package]
name = "sorting_lib"
version = "0.1.3"
authors = ["k m nandyka"]
edition = "2021"
description = "a rust lib implementing sort algorithm?"
license = "MIT"
repository = "https://github.com/mornsoltice/sorting-lib"
readme = "README.MD"

[dependencies]
